//go:build ignore
// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
	"fmt"
	"os"

	"github.com/mailru/easyjson/gen"

	pkg "github.com/wasm-automation/ruby-wasmer/go/types"
)

func main() {
	g := gen.NewGenerator("types_easyjson.go")
	g.SetPkg("types", "github.com/wasm-automation/ruby-wasmer/go/types")
	g.UseSnakeCase()
	g.Add(pkg.EasyJSON_exporter_Ticket(nil))
	if err := g.Run(os.Stdout); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
